In [3]:
import numpy as np

arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# indexing is same as in python
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[1:3] # start point : end point (not included)

array([2, 3])

In [6]:
arr[:-4]

array([1, 2, 3, 4, 5, 6])

In [9]:
arr[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[::2] # start to end with step 2

array([1, 3, 5, 7, 9])

#### Slicing 2d matrix

In [12]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [18]:
arr[3][3] 

# arr[rowIndex][ColIndex] to get an element
# if you only give row it will print whole row

# OR

# arr[rowIndex,ColIndex]

np.int64(19)

In [19]:
arr[3,3]

np.int64(19)

In [20]:
# slicng
# arr[rowStartIndex : rowEndIndex , ColStartIndex : ColEndIndex]
# Note : EndIndex will not be included

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [21]:
arr[1:4,0:3]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])