In [2]:
import numpy as np
import pandas as pd

In [3]:
arr = np.array([1,2,3,4])

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
arr.dtype

dtype('int64')

In [6]:
array2d = [[1,2,3],[4,5,6],[7,8,9]]
npArray2D = np.array(array2d)
npArray2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr2 = np.arange(0,11,2)
arr2

array([ 0,  2,  4,  6,  8, 10])

In [8]:
arr3 = np.zeros(5) # 5 zero
arr3

array([0., 0., 0., 0., 0.])

In [9]:
# zero matrix
arr4 = np.zeros((4,4)) # 4 rows 4 columns
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
arr4.dtype

dtype('float64')

In [12]:
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [13]:
arr = np.ones((2,6)) # 2 row 6 columns
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
# evenly spaced elements
# from 1 to 10 , 10 such evenly elements
arr = np.linspace(1,10,10) 
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# random number generation

np.random.rand(5) # 5 random numbers [vector] between 0-1 [normalization]



array([0.12141037, 0.61582725, 0.01526215, 0.38212832, 0.85553005])

In [25]:
np.random.randn(10) # 5 random element between -3 to 3 [standardization] 

array([-0.43277111, -0.31897029, -0.63645999, -0.80346902,  0.80382679,
       -1.01895676,  2.75030774,  0.87397589, -1.17094971, -0.40735876])

In [28]:
np.random.randint(10) # random number between 0 to 10

3

In [29]:
# if you want an array
np.random.randint(0,10,5) # between 0 to 10 , 5 random integers array

array([5, 3, 2, 7, 7], dtype=int32)

#### Attributes

In [32]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape # rows , column

(3, 3)

In [36]:
arr.size # total number of elements

9

In [37]:
arr.dtype # datatype of data inside array 

dtype('int64')

In [39]:
arr.ndim # dimension of array

2

#### Methods

In [40]:
arr.min()

np.int64(1)

In [41]:
arr.max()

np.int64(9)

In [42]:
arr.sum() # sum of all elements

np.int64(45)

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
np.sum(arr,axis=0) # column wise sum of each column

# asix = 0 means columns
# asix = 1 means rows

array([12, 15, 18])

In [46]:
np.sum(arr,axis=1) # column wise sum of each rows

array([ 6, 15, 24])

In [47]:
arr.mean() # average 

np.float64(5.0)

In [48]:
arr.std() # atandard deviation

np.float64(2.581988897471611)

In [ ]:
# find index of max element in array
arr.argmax()

np.int64(8)

In [50]:
# find index of min element in array
arr.argmin()

np.int64(0)

#### Reshape and resizing

In [52]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [53]:
# reshape
# you should metion correct number of columns and rows 
# which can occupy exact number of element you have
# else it throw an error
# i have 30 elements to 5x6 or 6x5 array would get the job done
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [54]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [56]:
# arr does not change you need to assign it to arr if you want 
# to make changes
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])